name: "Run Tests"

on:
  create: # Branch (so that the Docker image tags exist for a new branch when pushed)
          # But not sure if this means tags will be run twice (one for create:, one for push: tags) 
    branches: # Only on paths above
      - '**'

jobs:
  main:
    name: 'Main job'
    steps:
      - name: 'Main Step'
        run: echo "Run ref ${GITHUB_REF}"
